# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  ctdc-base-vanilla:
    type: boolean
    default: false
  ctdc-base-vsc:
    type: boolean
    default: false
  ctdc-base-fleet:
    type: boolean
    default: false
  ctdc-base-vsc-fleet:
    type: boolean
    default: false
  ctdc-node-vanilla:
    type: boolean
    default: false
  ctdc-node-vsc:
    type: boolean
    default: false
  ctdc-node-fleet:
    type: boolean
    default: false
  ctdc-node-vsc-fleet:
    type: boolean
    default: false
  ctdc-ccpp-vanilla:
    type: boolean
    default: false
  ctdc-ccpp-vsc:
    type: boolean
    default: false
  ctdc-ccpp-fleet:
    type: boolean
    default: false
  ctdc-ccpp-vsc-fleet:
    type: boolean
    default: false

executors:
  vm-build-amd64:
    environment:
      ARCH_TAG : amd64
      BUILDX_PLATFORMS : linux/amd64
    machine:
        image: ubuntu-2004:current
        docker_layer_caching: true
    resource_class: medium
  
  vm-build-arm64:
    environment:
      ARCH_TAG : arm64
      BUILDX_PLATFORMS : linux/arm64/v8
    machine:
        image: ubuntu-2004:current
        docker_layer_caching: true
    resource_class: arm.medium
  
  docker-other:
    docker:
      - image: cimg/base:current
    resource_class : small

jobs:

  DockerBuild-amd64:
      parameters:
        os:
          type: string
      executor: vm-build-amd64
      steps:
      - checkout
      - run :
          name: Build Docker image
          command: cd docker/$D_IMG/$FLAVOUR/<< parameters.os >> && docker buildx build --platform $BUILDX_PLATFORMS -t $REPO/$D_IMG:<< parameters.os >>-$FLAVOUR-$ARCH_TAG .
      - run :
          name: Publish Docker Image to Docker Hub
          command: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD && docker push $REPO/$D_IMG:<< parameters.os >>-$FLAVOUR-$ARCH_TAG
  
  DockerBuild-arm64:
      parameters:
        os:
          type: string
      executor: vm-build-arm64
      steps:
      - checkout
      - run :
          name: Build Docker image
          command: cd docker/$D_IMG/$FLAVOUR/<< parameters.os >> && docker buildx build --platform $BUILDX_PLATFORMS -t $REPO/$D_IMG:<< parameters.os >>-$FLAVOUR-$ARCH_TAG .
      - run :
          name: Publish Docker Image to Docker Hub
          command: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD && docker push $REPO/$D_IMG:<< parameters.os >>-$FLAVOUR-$ARCH_TAG
  
  DockerPublish-multiarch:
      parameters:
        os:
          type: string
      executor: docker-other
      steps:
        - setup_remote_docker :
           docker_layer_caching: true
           version : 20.10.14
        - run :
            name: Publish MultiArch
            command: |
              export DOCKER_CLI_EXPERIMENTAL=enabled
              docker manifest create $REPO/$D_IMG:<< parameters.os >>-$FLAVOUR $REPO/$D_IMG:<< parameters.os >>-$FLAVOUR-amd64 $REPO/$D_IMG:<< parameters.os >>-$FLAVOUR-arm64
              docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD && docker manifest push $REPO/$D_IMG:<< parameters.os >>-$FLAVOUR
              
  DeleteTempImage:
    parameters:
        os:
          type: string
    executor: docker-other
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run :
          name : Get Auth Token and Delete amd64 image
          command : |
            export TOKEN=`curl -s -H "Content-Type: application/json" -X POST -H "Content-Type: application/json" -d '{"username": "'$DOCKER_LOGIN'", "password": "'$DOCKER_PASSWORD'"}' "https://hub.docker.com/v2/users/login/" | jq -r .token`
            echo $TOKEN
            curl "https://hub.docker.com/v2/repositories/$REPO/$D_IMG/tags/<< parameters.os >>-$FLAVOUR-amd64/" -X DELETE -H "Authorization: JWT ${TOKEN}"
            curl "https://hub.docker.com/v2/repositories/$REPO/$D_IMG/tags/<< parameters.os >>-$FLAVOUR-arm64/" -X DELETE -H "Authorization: JWT ${TOKEN}"

  

workflows:

  ctdc-base-vanilla:
    when: << pipeline.parameters.ctdc-base-vanilla >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-base
            - vanilla
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-base
            - vanilla
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-base
            - vanilla
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-base
            - vanilla

  ctdc-base-vsc:
    when: << pipeline.parameters.ctdc-base-vsc >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-base
            - vsc
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-base
            - vsc
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-base
            - vsc
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-base
            - vsc

  ctdc-base-fleet:
    when: << pipeline.parameters.ctdc-base-fleet >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-base
            - fleet
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-base
            - fleet
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-base
            - fleet
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-base
            - fleet

  ctdc-base-vsc-fleet:
    when: << pipeline.parameters.ctdc-base-vsc-fleet >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-base
            - vsc-fleet
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-base
            - vsc-fleet
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-base
            - vsc-fleet
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-base
            - vsc-fleet


  ctdc-node-vanilla:
    when: << pipeline.parameters.ctdc-node-vanilla >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-node
            - vanilla
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-node
            - vanilla
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-node
            - vanilla
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-node
            - vanilla

  ctdc-node-vsc:
    when: << pipeline.parameters.ctdc-node-vsc >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-node
            - vsc
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-node
            - vsc
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-node
            - vsc
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-node
            - vsc

  ctdc-node-fleet:
    when: << pipeline.parameters.ctdc-node-fleet >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-node
            - fleet
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-node
            - fleet
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-node
            - fleet
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-node
            - fleet

  ctdc-node-vsc-fleet:
    when: << pipeline.parameters.ctdc-node-vsc-fleet >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-node
            - vsc-fleet
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-node
            - vsc-fleet
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-node
            - vsc-fleet
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-node
            - vsc-fleet
            
  
  ctdc-ccpp-vanilla:
    when: << pipeline.parameters.ctdc-ccpp-vanilla >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-ccpp
            - vanilla
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-ccpp
            - vanilla
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-ccpp
            - vanilla
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-ccpp
            - vanilla

  ctdc-ccpp-vsc:
    when: << pipeline.parameters.ctdc-ccpp-vsc >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-ccpp
            - vsc
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-ccpp
            - vsc
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-ccpp
            - vsc
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-ccpp
            - vsc

  ctdc-ccpp-fleet:
    when: << pipeline.parameters.ctdc-ccpp-fleet >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-ccpp
            - fleet
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-ccpp
            - fleet
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-ccpp
            - fleet
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-ccpp
            - fleet

  ctdc-ccpp-vsc-fleet:
    when: << pipeline.parameters.ctdc-ccpp-vsc-fleet >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-ccpp
            - vsc-fleet
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-ccpp
            - vsc-fleet
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-ccpp
            - vsc-fleet
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-ccpp
            - vsc-fleet