              docker/ctdc-php/vanilla/.* ctdc-php-vanilla true
              docker/ctdc-php/vsc/.* ctdc-php-vsc true
              docker/ctdc-php/fleet/.* ctdc-php-fleet true
              docker/ctdc-php/vsc-fleet/.* ctdc-php-vsc-fleet true

  ctdc-php-vanilla:
    type: boolean
    default: false
  ctdc-php-vsc:
    type: boolean
    default: false
  ctdc-php-fleet:
    type: boolean
    default: false
  ctdc-php-vsc-fleet:
    type: boolean
    default: false

  ctdc-php-vanilla:
    when: << pipeline.parameters.ctdc-php-vanilla >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-php
            - vanilla
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-php
            - vanilla
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-php
            - vanilla
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-php
            - vanilla

  ctdc-php-vsc:
    when: << pipeline.parameters.ctdc-php-vsc >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-php
            - vsc
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-php
            - vsc
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-php
            - vsc
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-php
            - vsc

  ctdc-php-fleet:
    when: << pipeline.parameters.ctdc-php-fleet >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-php
            - fleet
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-php
            - fleet
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-php
            - fleet
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-php
            - fleet

  ctdc-php-vsc-fleet:
    when: << pipeline.parameters.ctdc-php-vsc-fleet >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-php
            - vsc-fleet
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-php
            - vsc-fleet
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-php
            - vsc-fleet
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-php
            - vsc-fleet