              docker/ctdc-rust/vanilla/.* ctdc-rust-vanilla true
              docker/ctdc-rust/vsc/.* ctdc-rust-vsc true
              docker/ctdc-rust/fleet/.* ctdc-rust-fleet true
              docker/ctdc-rust/vsc-fleet/.* ctdc-rust-vsc-fleet true

  ctdc-rust-vanilla:
    type: boolean
    default: false
  ctdc-rust-vsc:
    type: boolean
    default: false
  ctdc-rust-fleet:
    type: boolean
    default: false
  ctdc-rust-vsc-fleet:
    type: boolean
    default: false

  ctdc-rust-vanilla:
    when: << pipeline.parameters.ctdc-rust-vanilla >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-rust
            - vanilla
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-rust
            - vanilla
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-rust
            - vanilla
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-rust
            - vanilla

  ctdc-rust-vsc:
    when: << pipeline.parameters.ctdc-rust-vsc >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-rust
            - vsc
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-rust
            - vsc
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-rust
            - vsc
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-rust
            - vsc

  ctdc-rust-fleet:
    when: << pipeline.parameters.ctdc-rust-fleet >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-rust
            - fleet
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-rust
            - fleet
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-rust
            - fleet
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-rust
            - fleet

  ctdc-rust-vsc-fleet:
    when: << pipeline.parameters.ctdc-rust-vsc-fleet >>
    jobs:
      - DockerBuild-amd64 :
          name : build-amd64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-rust
            - vsc-fleet
      - DockerBuild-arm64 :
          name : build-arm64-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          context : 
            - DockerHub
            - ctdc-rust
            - vsc-fleet
      - DockerPublish-multiarch :
          name : publish-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires :
            - build-arm64-<< matrix.os >>
            - build-amd64-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-rust
            - vsc-fleet
      - DeleteTempImage:
          name : clearTemp-<< matrix.os >>
          matrix:
            parameters:
              os : ["debian","fedora","ubuntu"]
          requires:
            - publish-<< matrix.os >>
          context : 
            - DockerHub
            - ctdc-rust
            - vsc-fleet