              docker/ctdc-python/no-vsc/debian/Dockerfile ctdc-python-debian-no-vsc true
              docker/ctdc-python/no-vsc/fedora/Dockerfile ctdc-python-fedora-no-vsc true
              docker/ctdc-python/no-vsc/ubuntu/Dockerfile ctdc-python-ubuntu-no-vsc true
              docker/ctdc-python/vsc/debian/Dockerfile ctdc-python-debian-vsc true
              docker/ctdc-python/vsc/fedora/Dockerfile ctdc-python-fedora-vsc true
              docker/ctdc-python/vsc/ubuntu/Dockerfile ctdc-python-ubuntu-vsc true

  ctdc-python-debian-no-vsc:
    type: boolean
    default: false
  ctdc-python-fedora-no-vsc:
    type: boolean
    default: false
  ctdc-python-ubuntu-no-vsc:
    type: boolean
    default: false
  ctdc-python-debian-vsc:
    type: boolean
    default: false
  ctdc-python-fedora-vsc:
    type: boolean
    default: false
  ctdc-python-ubuntu-vsc:
    type: boolean
    default: false

ctdc-python-debian-no-vsc:
    when: << pipeline.parameters.ctdc-python-debian-no-vsc >>
    jobs:
      - DockerBuild-amd64 :
          context : 
            - DockerHub
            - Debian
            - ctdc-python
            - no-vsc
      - DockerBuild-arm64 :
          context : 
            - DockerHub
            - Debian
            - ctdc-python
            - no-vsc
      - DockerPublish-multiarch :
          requires :
            - DockerBuild-arm64
            - DockerBuild-amd64
          context : 
            - DockerHub
            - Debian
            - ctdc-python
            - no-vsc
      - DeleteTempImage-amd64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Debian
            - ctdc-python
            - no-vsc
      - DeleteTempImage-arm64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Debian
            - ctdc-python
            - no-vsc

  ctdc-python-fedora-no-vsc:
    when: << pipeline.parameters.ctdc-python-fedora-no-vsc >>
    jobs:
      - DockerBuild-amd64 :
          context : 
            - DockerHub
            - Fedora
            - ctdc-python
            - no-vsc
      - DockerBuild-arm64 :
          context : 
            - DockerHub
            - Fedora
            - ctdc-python
            - no-vsc
      - DockerPublish-multiarch :
          requires :
            - DockerBuild-arm64
            - DockerBuild-amd64
          context : 
            - DockerHub
            - Fedora
            - ctdc-python
            - no-vsc
      - DeleteTempImage-amd64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Fedora
            - ctdc-python
            - no-vsc
      - DeleteTempImage-arm64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Fedora
            - ctdc-python
            - no-vsc

  ctdc-python-ubuntu-no-vsc:
    when: << pipeline.parameters.ctdc-python-ubuntu-no-vsc >>
    jobs:
      - DockerBuild-amd64 :
          context : 
            - DockerHub
            - Ubuntu
            - ctdc-python
            - no-vsc
      - DockerBuild-arm64 :
          context : 
            - DockerHub
            - Ubuntu
            - ctdc-python
            - no-vsc
      - DockerPublish-multiarch :
          requires :
            - DockerBuild-arm64
            - DockerBuild-amd64
          context : 
            - DockerHub
            - Ubuntu
            - ctdc-python
            - no-vsc
      - DeleteTempImage-amd64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Ubuntu
            - ctdc-python
            - no-vsc
      - DeleteTempImage-arm64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Ubuntu
            - ctdc-python
            - no-vsc
  
  ctdc-python-debian-vsc:
    when: << pipeline.parameters.ctdc-python-debian-vsc >>
    jobs:
      - DockerBuild-amd64 :
          context : 
            - DockerHub
            - Debian
            - ctdc-python
            - vsc
      - DockerBuild-arm64 :
          context : 
            - DockerHub
            - Debian
            - ctdc-python
            - vsc
      - DockerPublish-multiarch :
          requires :
            - DockerBuild-arm64
            - DockerBuild-amd64
          context : 
            - DockerHub
            - Debian
            - ctdc-python
            - vsc
      - DeleteTempImage-amd64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Debian
            - ctdc-python
            - vsc
      - DeleteTempImage-arm64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Debian
            - ctdc-python
            - vsc
  
  ctdc-python-fedora-vsc:
    when: << pipeline.parameters.ctdc-python-fedora-vsc >>
    jobs:
      - DockerBuild-amd64 :
          context : 
            - DockerHub
            - Fedora
            - ctdc-python
            - vsc
      - DockerBuild-arm64 :
          context : 
            - DockerHub
            - Fedora
            - ctdc-python
            - vsc
      - DockerPublish-multiarch :
          requires :
            - DockerBuild-arm64
            - DockerBuild-amd64
          context : 
            - DockerHub
            - Fedora
            - ctdc-python
            - vsc
      - DeleteTempImage-amd64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Fedora
            - ctdc-python
            - vsc
      - DeleteTempImage-arm64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Fedora
            - ctdc-python
            - vsc

  ctdc-python-ubuntu-vsc:
    when: << pipeline.parameters.ctdc-python-ubuntu-vsc >>
    jobs:
      - DockerBuild-amd64 :
          context : 
            - DockerHub
            - Ubuntu
            - ctdc-python
            - vsc
      - DockerBuild-arm64 :
          context : 
            - DockerHub
            - Ubuntu
            - ctdc-python
            - vsc
      - DockerPublish-multiarch :
          requires :
            - DockerBuild-arm64
            - DockerBuild-amd64
          context : 
            - DockerHub
            - Ubuntu
            - ctdc-python
            - vsc
      - DeleteTempImage-amd64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Ubuntu
            - ctdc-python
            - vsc
      - DeleteTempImage-arm64:
          requires:
            - DockerPublish-multiarch
          context : 
            - DockerHub
            - Ubuntu
            - ctdc-python
            - vsc